src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>language__c</fullName>
        <label>language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>survey_date__c</fullName>
        <label>survey date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Org_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ContactSurveySupportedLanguages__c</fullName>
        <label>ContactSurveySupportedLanguages</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Org Settings</label>
</CustomObject>

src/objects/Product_Country_Price__c.object
<CustomObject>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <label>ATM Fee in other currencies</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <label>Card Replacement Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_per_Calendar_Month__c</fullName>
        <label>Cost per Calendar Month</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Product Country Prices</relationshipLabel>
        <relationshipName>Product_Country_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Country Prices</relationshipLabel>
        <relationshipName>Product_Country_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Country Price</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Product Country Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Country Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {
    
    public static Contact createContactForSurvey()
    {
        Contact c = new Contact(
            FirstName = 'fname',
            LastName = 'lname',
            email = 'email@email.com',
            language__c = 'en'
        );
        c.survey_date__c = Date.Today() - 1;
        insert c;
        return c;
    }
    
    public static void create50ContactsForSurvey()
    {
        List<Contact> contactsIns = new List<Contact>();
               
        for(Integer i = 1; i <= 50; i++)
        {
            Contact c = new Contact(
                FirstName = 'fname' + string.valueOf(i),
                LastName = 'lname',
                email = 'email' + string.valueOf(i) + '@email.com',
                language__c = 'en'
            );    
            c.survey_date__c = Date.Today() - 1;
            contactsIns.add(c);  
        }
        insert contactsIns;
    }
    
    public static void createSurveyCustomSettings()
    {
        Org_Settings__c os = new Org_Settings__c();
        os.ContactSurveySupportedLanguages__c = 'en;de';
        insert os;
    }
    
    public static EmailTemplate createSurveyEmailTemplate()
    {
        for(EmailTemplate existing : [select id, developerName, TemplateType from EmailTemplate where developerName = 'SurveyTemplate_en'])
        {
            return existing;
        }
        
        EmailTemplate e = new EmailTemplate (
            developerName = 'SurveyTemplate_en', 
            FolderId = UserInfo.getOrganizationId(), 
            TemplateType = 'Text',
            Body = 'Hey {!Contact.FirstName}, Please fill out our survey: http://n26.com/survey/{!Contact.Id}',
            Name = 'Survey Template EN'
        ); 
        
        insert e;
        return e;
    }
    
    public static Product2 createProduct()
    {
        Product2 p = new Product2(
            Name = 'Standard'
        );
        insert p;
        return p;
    }
    
    public static Country__c createCountry()
    {
        Country__c c = new Country__c(
            Name = 'Germany',
            Country_Code__c = 'de'
        );
        insert c;
        return c;
    }
    
    public static Contact createContact(String ProductId, String CountryId)
    {
        Contact c = new Contact(
            FirstName = 'FirstName',
            LastName = 'LastName',
            Home_Country__c = CountryId,
            Product__c = ProductId
        );
        insert c;
        return c;
    }
    
    public static Case createCase(String ContactId)
    {
        Case c = new Case(
            Subject = 'TestCase',
            ContactId = ContactId
        );
        insert c;
        return c;
    }
    
    public static Product_Country_Price__c createProductPricing(String ProductId, String CountryId)
    {
    	Product_Country_Price__c pcp = new Product_Country_Price__c(
            Product__c = ProductId, 
            Country__c = CountryId, 
            Cost_per_Calendar_Month__c = 0, 
            Card_Replacement_Cost__c = 0.017, 
            ATM_Fee_in_other_currencies__c = 6
		);
    	insert pcp;
        return pcp;
    }
}