src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Country_Price__c.object
<CustomObject>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <label>ATM Fee in other currencies</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <label>Card Replacement Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_per_Calendar_Month__c</fullName>
        <label>Cost per Calendar Month</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Product Country Prices</relationshipLabel>
        <relationshipName>Product_Country_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Country Prices</relationshipLabel>
        <relationshipName>Product_Country_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Country Price</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Product Country Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Country Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductPricingController.cls
public class ProductPricingController {

    @AuraEnabled
 	public static Product_Country_Price__c getPricing(String caseId) {
 		
    for( Case c : [Select Id, ContactId, Contact.Home_Country__c, Contact.Product__c from Case where id = :caseId] )
    {
        if(c.Contact.Home_Country__c != NULL && c.Contact.Product__c != NULL)
        {
            for(Product_Country_Price__c pcp : [select Id, Product__c, Country__c, Cost_per_Calendar_Month__c, 
                                                		Card_Replacement_Cost__c, ATM_Fee_in_other_currencies__c
                                                from Product_Country_Price__c 
                                                where Product__c = :c.Contact.Product__c AND Country__c = :c.Contact.Home_Country__c])
            {
                return pcp;
            }
        }
    }
    
 	return NULL;
 }
    
    
}