src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Country_Price__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Product Country Prices</relationshipLabel>
        <relationshipName>Product_Country_Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Country Price</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Product Country Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Country Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductPricingController_TEST.cls
@IsTest
public class ProductPricingController_TEST {

    private static testmethod void test_getPricing() 
    {
    	Product2 p = TestDataFactory.createProduct();
        Country__c c = TestDataFactory.createCountry();
        Contact con = TestDataFactory.createContact(p.Id, c.Id);
        Case cs = TestDataFactory.createCase(con.Id);
        Product_Country_Price__c pcp = TestDataFactory.createProductPricing(p.Id, c.Id);
        
        Test.startTest();

        	Product_Country_Price__c pcp2 = ProductPricingController.getPricing(cs.Id);
        
        Test.stopTest();
        
        System.assertEquals(pcp.Id, pcp2.Id);
    }
    
}